@startuml Arkanoid

class Jugador {
  + Jugador(RenderWindow& ventana)
  + MoverDerecha()
  + MoverIzquierda()
  + Dibujar(RenderWindow& ventana)
  + EscalarPaleta()
  + RestaurarEscala()
  + GetPosition() : FloatRect
  - paleta : RectangleShape
}

class Puntuaje {
  - puntuacion: int
  - textoPuntuacion: sf::Text
  - fuente: sf::Font
  + Puntuaje()
  + IncrementarPuntuacion(puntos: int)
  + ReiniciarPuntuacion()
  + Draw(window: RenderWindow&)
}

class Bloque {
  + Bloque()
  + Inicializar(float x, float y, bool estado, Color color)
  + Colision(FloatRect bolaPos) : bool
  + Dibujar(RenderWindow& ventana)
  + GetPosition() : Vector2f
  - bloque : RectangleShape
  - estado : bool
}

class Bola {
  + Bola(RenderWindow& ventana)
  + Mover()
  + Rebotar()
  + Dibujar(RenderWindow& ventana)
  + GetPosition() : FloatRect
  + CambiarDireccionX()
  + CambiarDireccionY()
  - bola : CircleShape
  - velDirBola : Vector2f
}

class Pastilla {
  + Pastilla()
  + Inicializar(float x, float y)
  + Mover()
  + Dibujar(RenderWindow& ventana)
  + Colision(FloatRect jugadorPos) : bool
  + GetEstado() : bool
  + Desactivar()
  - pastilla : RectangleShape
  - estado : bool
}

class Juego {
  + Iniciar()
  + EstaEjecutandose()
}

Jugador "1" *-- "1" Bola
Jugador "1" o-- "1" Bola
Jugador "1" o-- "0..1*" Bloque
Jugador "1" *-- Pastilla
Jugador "1" o-- "0..1" Pastilla
Jugador "1" *-- "0..1" Puntuaje

Juego "1" *-- "1" Jugador
Juego "1" *-- "0..1*" Bloque
Juego "1" *-- "1" Bola
Juego "1" *-- "0..1" Pastilla
Juego "1" *-- "1" Puntuaje

Bloque "1" *-- "0..1" Puntuaje
Bola "1" o-- "1" Bloque
Pastilla "1" o-- "1" Bola

@enduml